# Generated by Django 3.2.6 on 2021-11-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211107_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس آی پی', 'verbose_name_plural': 'آدرس های آی پی'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
